[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
pluginYml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "plugin_yml" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "run_paper" }

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
mccoroutines = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-bukkit-api", version.ref = "mccoroutine" }
mccoroutinesCore = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-bukkit-core", version.ref = "mccoroutine" }

[versions]
paper = "1.21.3-R0.1-SNAPSHOT"
kotlin = "2.1.0"
plugin_yml = "0.6.0"
run_paper = "2.3.1"
coroutines = "1.9.0"
mccoroutine = "2.20.0"